# Generated by Django 5.1.2 on 2024-10-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_descriptions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_descriptions_ru',
            field=models.TextField(null=True),
        ),
    ]
